### ISSUE TITLE
GAE: yarn build failing due to accidental cache hit

### ISSUE THREAD

**Issue by yuzeh** [GoogleCloudPlatform/buildpacks#34]
Sorry that this bug is a bit vague, I've been trying to investigate the issue this morning and it led me to here.

I have an app that's built with node12+yarn and am trying to deploy to Google App Engine via `gcloud app deploy`. The deploy has been failing with a link to Cloud Build. When I go to the Cloud Build log, I see this:

```
Step #5 - "builder": === Node.js - Yarn gcp-build (google.nodejs.yarn-gcp-build@0.9.0) ===
Step #5 - "builder": ————————————————————————————————————————————————————————————————————————————————
Step #5 - "builder": Running "node -v"
Step #5 - "builder": v12.16.2
Step #5 - "builder": Done "node -v" (73.163373ms)
Step #5 - "builder": DEBUG: Current dependency hash: "4d6a49a8d49558ede7fad79ba7cf3608221ce03b9aa7b1c13ab430fd2b24a316"
Step #5 - "builder": DEBUG:   Cache dependency hash: "4d6a49a8d49558ede7fad79ba7cf3608221ce03b9aa7b1c13ab430fd2b24a316"
Step #5 - "builder": Dependencies cache hit, skipping installation.
Step #5 - "builder": DEBUG: ***** CACHE HIT: "dev dependencies"
Step #5 - "builder": Due to cache hit, package.json scripts will not be run. To run the scripts, disable caching.
```

The hash here remains the same after deploying again with updated `package.json` and `yarn.lock` files.

Code searching for `CACHE HIT` and `dev dependencies` led me to this repo.  I've been able to work around this with `gcloud beta app deploy --no-cache` but figured this would be helpful for someone else running into the issue.

Feel free to close if this report is not relevant to this repo.

**Comment by lukasberger** [comment]
Thank you for the report. Is it possible that your package.json was not updated but no dependencies changes so yarn.lock stayed the same? The way we generate the cache key is by hashing the version of Node and contents of yarn.lock, which would lead to a cache hit in this case. We've fixed in the the npm/yarn buildapcks, but unfortunately seem to have missed the gcp-build buildpacks.

**Comment by lukasberger** [comment]
This should now be fixed at HEAD, but it may take some time to see the changes in GAE. In the interim please use the `--no-cache` flag. If this continues to be an issue for you, please feel free to reopen.

**Comment by hjr3** [comment]
> Thank you for the report. Is it possible that your package.json was updated but no dependencies changed so yarn.lock stayed the same? The way we generate the cache key is by hashing the version of Node and contents of yarn.lock, which would lead to a cache hit in this case. We've fixed this in the the npm/yarn buildapcks, but unfortunately seem to have missed the gcp-build buildpacks.

@lukasberger We also hit this bug. I double checked and we definitely updated our `package-lock.json` file. I also checked that the build manifest included the package-lock.json file. I am all for including `package.json` in when computing the hash, but it feels like there is a deeper bug here.

**Comment by yuzeh** [comment]
> > Thank you for the report. Is it possible that your package.json was updated but no dependencies changed so yarn.lock stayed the same? The way we generate the cache key is by hashing the version of Node and contents of yarn.lock, which would lead to a cache hit in this case. We've fixed this in the the npm/yarn buildapcks, but unfortunately seem to have missed the gcp-build buildpacks.
> 
> @lukasberger We also hit this bug. I double checked and we definitely updated our `package-lock.json` file. I also checked that the build manifest included the `package-lock.json` file. I am all for including `package.json` in when computing the hash, but it feels like there is a deeper bug here.

Agree with @hjr3 on this. I think the issue is a bit deeper than just "`package.json` wasn't added to the list of files to `sha256`" as https://github.com/GoogleCloudPlatform/buildpacks/commit/d1b3768b9ddc6247cf92c96ace96fefe87a835ee does. 

The issue I was running into yesterday still happened despite updating my `yarn.lock` file.

@lukasberger

**Comment by yuzeh** [comment]
My understanding of golang is very basic, but I think this might be the smoking gun?

https://github.com/GoogleCloudPlatform/buildpacks/blob/8f3e10b/pkg/gcpbuildpack/hash.go#L51

This function hashes a `string` parameter as the value of the string and not the contents of the file that the `string` points to.

**Comment by lukasberger** [comment]
Yes, that is indeed the issue. We're in the process of reverting the most recent release in GAE, which introduced this regression. Sorry about that!
